/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chapters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start_download"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/download/cancel/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/download/events/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/download/file/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["file"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/download/status/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proxy-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["proxy_image"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_sources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Cancelled: {
            status: string;
            /** Format: uuid */
            task_id: string;
        };
        Capabilities: {
            /** @description Headless browser available for managed challenges (not built yet). */
            browser: boolean;
            /** @description Output formats this build can produce. Filled in by the pipeline (Phase 2). */
            formats: string[];
            /** @description Chrome-impersonating client available for Cloudflare-fronted sources. */
            impersonation: boolean;
        };
        Chapter: {
            /** @description Source-specific identifier, opaque to the client. */
            id: string;
            /** @description Chapter label as the source shows it (`"12"`, `"12.5"`, `"Extra"`). */
            number: string;
            /** Format: int32 */
            pages?: number | null;
            title?: string | null;
        };
        ChapterRef: {
            id: string;
            /** @description Chapter label used for file names ("12", "12.5"). */
            number: string;
        };
        ChaptersResponse: {
            comic_id: string;
            source: string;
            total_chapters: number;
            volumes: components["schemas"]["Volume"][];
        };
        Comic: {
            cover?: null | components["schemas"]["Cover"];
            /** @description Source-specific identifier, opaque to the client. */
            id: string;
            /** @description Languages chapters are available in. */
            languages: string[];
            /** @description Localized titles keyed by language code. `en` when the source has one language. */
            title: {
                [key: string]: string;
            };
        };
        /** @description Where a cover image lives and which `Referer` (if any) the host expects. */
        Cover: {
            referer?: string | null;
            url: string;
        };
        DownloadAccepted: {
            events_url: string;
            file_url: string;
            message: string;
            state: components["schemas"]["TaskState"];
            /** @description Legacy field the old client displayed. */
            status: string;
            status_url: string;
            /** Format: uuid */
            task_id: string;
        };
        DownloadRequest: {
            chapters: components["schemas"]["ChapterRef"][];
            comic_title?: string;
            format?: components["schemas"]["Format"];
            lang?: string | null;
            /** @description Source id or slug. */
            source: string;
        };
        ErrorBody: {
            error: components["schemas"]["ErrorDetail"];
        };
        ErrorDetail: {
            /** @description Stable machine-readable code. */
            code: string;
            message: string;
            source?: string | null;
        };
        /**
         * @description Which fetch strategy a source needs to get past its front door.
         * @enum {string}
         */
        FetchTier: "plain" | "impersonate" | "browser";
        /** @enum {string} */
        Format: "pdf" | "cbz" | "cbr" | "epub";
        Health: {
            active_tasks: number;
            capabilities: components["schemas"]["Capabilities"];
            sources: components["schemas"]["SourceCounts"];
            status: string;
            /** Format: int64 */
            uptime_s: number;
            version: string;
        };
        SearchResponse: {
            /** @description Sources that failed, keyed by slug. A partial failure is still a 200. */
            errors: {
                [key: string]: components["schemas"]["ErrorDetail"];
            };
            /** @description Results keyed by source slug. */
            results: {
                [key: string]: components["schemas"]["Comic"][];
            };
        };
        SourceCapabilities: {
            chapters: boolean;
            download: boolean;
            needs_browser: boolean;
            search: boolean;
        };
        SourceCounts: {
            implemented: number;
            total: number;
        };
        SourceInfo: components["schemas"]["SourceMeta"] & {
            /** @description Legacy numeric identifier as a string, the form the old client sends. */
            legacy_id: string;
            status: components["schemas"]["SourceStatus"];
        };
        /**
         * @description Static description of a source. The numeric `id` is the legacy identifier the
         *     client has always sent (`"0"` to `"10"`); `slug` is the new stable name.
         */
        SourceMeta: {
            base_url: string;
            capabilities: components["schemas"]["SourceCapabilities"];
            /** Format: int32 */
            id: number;
            languages: string[];
            name: string;
            slug: string;
            speed: components["schemas"]["Speed"];
            tier: components["schemas"]["FetchTier"];
        };
        /** @enum {string} */
        SourceStatus: "ok" | "down" | "blocked" | "unknown";
        /**
         * @description How fast a source usually answers. Mirrors the tiers the old client hardcoded.
         * @enum {string}
         */
        Speed: "fastest" | "fast" | "slow";
        /** @enum {string} */
        TaskState: "PENDING" | "PROGRESS" | "SUCCESS" | "FAILURE" | "CANCELLED";
        /** @description Snapshot of a task. Superset of the shape the old client polls. */
        TaskStatus: {
            chapter_current: number;
            chapter_total: number;
            comic_title: string;
            content_type?: string | null;
            /**
             * Format: int64
             * @description Unix seconds.
             */
            created_at: number;
            error?: string | null;
            file_name?: string | null;
            /** Format: int64 */
            file_size?: number | null;
            format: components["schemas"]["Format"];
            /**
             * Format: int32
             * @description 0-100.
             */
            progress: number;
            source: string;
            state: components["schemas"]["TaskState"];
            /** @description Human readable progress message. */
            status: string;
            /** Format: uuid */
            task_id: string;
            /** @description Legacy alias of `chapter_total`. */
            total_chapters: number;
            /** @description Chapters that were skipped because their pages could not be resolved. */
            warnings?: string[];
            /** @description Legacy alias: the old client never used it, but the old API returned it. */
            zip_path?: string | null;
        };
        Volume: {
            chapters: components["schemas"]["Chapter"][];
            /** @description Display name, e.g. `"Vol 1"`. Sources without volumes use `"Vol 1"`. */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chapters: {
        parameters: {
            query: {
                /** @description Source id or slug. */
                source: string;
                /** @description Comic id as returned by search. */
                id: string;
                /** @description Chapter language for multi-language sources. Defaults to `en`. */
                lang?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChaptersResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    start_download: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadAccepted"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unsupported format on this server */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Source cannot download yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cancelled"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Already finished */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events stream of TaskStatus objects; closes on a terminal state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The archive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": unknown;
                };
            };
            /** @description Unknown task, failed task, or file already collected */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Task still running */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatus"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    proxy_image: {
        parameters: {
            query: {
                /** @description Absolute image URL. */
                url: string;
                /** @description Referer the host expects. */
                referer?: string | null;
                /** @description Legacy alias for `referer`. */
                hd?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The image bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": unknown;
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                /** @description Title to search for. */
                q: string;
                /** @description Source id, slug, or `all`. */
                source?: string;
                /** @description Preferred language code (only some sources honor it). */
                lang?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Empty query or unknown source */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Source not ported yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Source failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_sources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceInfo"][];
                };
            };
        };
    };
    list_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatus"][];
                };
            };
        };
    };
}
