services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 3
    ports:
      - "${WEB_PORT:-8000}:8000"
    env_file:
      - path: ./.env
        required: true # default
      - path: ./.env.production
        required: false
    volumes:
      - downloads_data:/app/Downloads
    depends_on:
      - redis

  worker:
    build: .
    command: python3 celery_worker.py
    env_file:
      - path: ./.env
        required: true # default
      - path: ./.env.production
        required: false
    volumes:
      - downloads_data:/app/Downloads
    depends_on:
      - redis

  redis:
    image: redis:alpine

volumes:
  downloads_data:
  
